name: "🐛 Bug Report"
description: "Report a bug or issue in the codebase"
title: "[Bug]: "
labels: ["🐛 bug", "📋 triage"]
assignees:
  - vectorcr
projects:
  - "Vector-Costa-Rica/10" # Vector Backlog Project

body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        Please provide detailed information about the bug you've encountered.

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "Provide a clear and concise description of the bug"
      placeholder: "Describe what the bug is and its impact on the system"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🔄 Steps to reproduce"
      description: "How can we reproduce this issue?"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected behavior"
      description: "What should have happened?"
      placeholder: "Describe what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "❌ Actual behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually happened"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "Select the impact level of this issue"
      options:
        - "🔥 p0-critical - Immediate attention required"
        - "🚨 p1-urgent - Address as soon as possible"
        - "⚡ p2-high - Plan to address soon"
        - "📊 p3-medium - Address in current sprint"
        - "📫 p4-low - Address when possible"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Issue Category"
      description: "Select the type of issue"
      options:
        - "🎯 core - Core functionality changes"
        - "🎨 ui-ux - User interface and experience changes"
        - "⚡ performance - Performance related changes"
        - "🔒 security - Security related changes"
        - "📱 mobile - Mobile specific changes"
        - "💾 database - Database related issues"
        - "🌐 api - API related issues"
        - "🧪 testing - Testing related issues"
        - "🔧 configuration - Configuration issues"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "🌍 Environment"
      description: "Where was this bug found?"
      options:
        - "Development"
        - "Staging"
        - "Production"
        - "Local"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📋 Relevant Logs"
      description: "Paste any relevant logs or error messages"
      placeholder: "Paste logs here..."

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "If applicable, add screenshots to help explain the problem"
      placeholder: "Drag and drop images here"

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the problem here"
      placeholder: "Any other information that might be relevant"

  - type: markdown
    attributes:
      value: |
        ---
        📋 This issue will be reviewed and prioritized by the team.
