name: "🐛 Bug Report"
description: "Report a bug or unexpected behavior"
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "A clear and concise description of the bug"
      placeholder: "What happened?"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected Behavior"
      description: "What you expected to happen"
      placeholder: "A clear and concise description of what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened"
      placeholder: "A clear and concise description of what actually happened"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "🖼️ Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      placeholder: "Add screenshots here"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: "🚨 Severity Level"
      description: "How severe is this bug?"
      options:
        - "Critical - System crash or data loss"
        - "High - Major functionality broken"
        - "Medium - Minor functionality broken"
        - "Low - Cosmetic or minor issue"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "💻 Environment"
      description: "Please complete the following information"
      placeholder: |
        - OS: [e.g. iOS, Windows]
        - Browser: [e.g. Chrome, Safari]
        - Version: [e.g. 22]
        - Device: [e.g. iPhone 6]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📋 Relevant Logs"
      description: "Any relevant logs or error messages"
      placeholder: "Paste any relevant logs here"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the problem here"
      placeholder: "Any additional information that might be relevant"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        This bug report will be reviewed and prioritized by the team.
