name: "📚 Documentation Request"
description: "Request documentation updates or improvements"
title: "[Docs]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request documentation improvements!

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "A clear and concise description of the documentation need"
      placeholder: "What documentation do you need?"
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: "📋 Current Documentation"
      description: "Describe the current state of the documentation"
      placeholder: "What documentation currently exists, if any?"
    validations:
      required: true

  - type: textarea
    id: desired-state
    attributes:
      label: "🎯 Desired Documentation"
      description: "Describe what documentation you need"
      placeholder: "What documentation would you like to see?"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "How important is this documentation?"
      options:
        - "Critical - Essential for system understanding"
        - "High - Important for user guidance"
        - "Medium - Helpful for clarity"
        - "Low - Nice to have"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Documentation Category"
      description: "What type of documentation is needed?"
      options:
        - "📖 user-guide - End user documentation"
        - "👩‍💻 technical - Technical documentation"
        - "🔧 api - API documentation"
        - "📋 process - Process documentation"
        - "🔍 troubleshooting - Troubleshooting guides"
        - "📚 reference - Reference documentation"
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: "👥 Target Audience"
      description: "Who is this documentation for?"
      placeholder: "Describe who will use this documentation"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the documentation request here"
      placeholder: "Any additional information that might be relevant"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        This documentation request will be reviewed and prioritized by the team.
