name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["🎯 feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - 🔥 p0-critical
        - 🚨 p1-urgent
        - ⚡ p2-high
        - 📊 p3-medium
        - 📫 p4-low
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: Tell us about the problem you're trying to solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: List any alternative solutions you've considered...

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How big is this feature?
      options:
        - 🐜 size-xs
        - 🦗 size-s
        - 🐇 size-m
        - 🦊 size-l
        - 🦌 size-xl
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.

  - type: markdown
    attributes:
      value: |
        This feature request will be reviewed and prioritized by the team.
