name: "🎯 Feature Request"
description: "Suggest a new feature or enhancement"
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "A clear and concise description of the feature you'd like to see"
      placeholder: "What would you like to see implemented?"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "❓ Problem Statement"
      description: "What problem does this feature solve?"
      placeholder: "Describe the problem this feature would solve"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "💡 Proposed Solution"
      description: "Describe how you envision this feature working"
      placeholder: "Describe your proposed solution"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternatives Considered"
      description: "Have you considered any alternative solutions?"
      placeholder: "Describe any alternative solutions you've considered"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "How important is this feature?"
      options:
        - "Critical - Essential for core functionality"
        - "High - Important for user experience"
        - "Medium - Valuable enhancement"
        - "Low - Nice to have"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Feature Category"
      description: "What type of feature is this?"
      options:
        - "🎯 core - Core functionality"
        - "🎨 ui-ux - User interface/experience"
        - "📱 mobile - Mobile specific"
        - "🌐 api - API related"
        - "💾 database - Database related"
        - "🔧 configuration - Configuration related"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "📊 Impact"
      description: "Who would benefit from this feature?"
      placeholder: "Describe who would benefit and how"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the feature request here"
      placeholder: "Any additional information that might be relevant"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        This feature request will be reviewed and prioritized by the team.
