name: "✨ Minor Enhancement"
description: "Request a small improvement or enhancement"
title: "[Enhancement]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement!

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "A clear and concise description of the enhancement"
      placeholder: "What enhancement would you like to see?"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: "📋 Current Behavior"
      description: "Describe how things work currently"
      placeholder: "Describe the current behavior or functionality"
    validations:
      required: true

  - type: textarea
    id: desired-behavior
    attributes:
      label: "🎯 Desired Behavior"
      description: "Describe how you'd like things to work"
      placeholder: "Describe the desired behavior or functionality"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "How important is this enhancement?"
      options:
        - "Critical - Essential for usability"
        - "High - Important for user experience"
        - "Medium - Valuable improvement"
        - "Low - Nice to have"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🏷️ Enhancement Category"
      description: "What type of enhancement is this?"
      options:
        - "🎨 ui-ux - User interface/experience"
        - "⚡ performance - Performance improvement"
        - "🔧 configuration - Configuration option"
        - "📱 mobile - Mobile specific"
        - "🌐 api - API related"
        - "💾 database - Database related"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "📊 Impact"
      description: "Who would benefit from this enhancement?"
      placeholder: "Describe who would benefit and how"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the enhancement here"
      placeholder: "Any additional information that might be relevant"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        This enhancement request will be reviewed and prioritized by the team.
