name: "🔧 Minor Enhancement"
description: "Request a small improvement or change"
title: "[Enhancement]: "
labels: ["🔄 enhancement", "📋 triage"]
assignees:
  - vectorcr
projects:
  - "Vector-Costa-Rica/10" # Vector Backlog Project

body:
  - type: markdown
    attributes:
      value: |
        # Minor Enhancement
        Please provide details about the small improvement you're requesting.

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "What small change or improvement do you need?"
      placeholder: "Describe the minor enhancement you're requesting"
    validations:
      required: true

  - type: dropdown
    id: enhancement-type
    attributes:
      label: "🔧 Enhancement Type"
      description: "What type of enhancement is this?"
      options:
        - "📝 Text Update"
        - "🖼️ Image Update"
        - "🔧 Configuration Change"
        - "📊 Data Update"
        - "🔍 Content Update"
        - "⚙️ Minor Feature Tweak"
        - "🎨 Style Update"
        - "📱 Mobile Adjustment"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "How urgent is this enhancement?"
      options:
        - "🔥 p0-critical - Immediate attention required"
        - "🚨 p1-urgent - Address as soon as possible"
        - "⚡ p2-high - Plan to address soon"
        - "📊 p3-medium - Address in current sprint"
        - "📫 p4-low - Address when possible"
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: "📏 Estimated Size"
      description: "How complex is this enhancement?"
      options:
        - "🐜 size-xs - Extra small (< 2 hours)"
        - "🦗 size-s - Small (< 4 hours)"
        - "🐇 size-m - Medium (1 day)"
        - "🦊 size-l - Large (2-3 days)"
        - "🦌 size-xl - Extra large (> 3 days)"
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: "📋 Current State"
      description: "What is the current state that needs to be changed?"
      placeholder: "Describe what currently exists that needs to be enhanced"
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: "💡 Proposed Changes"
      description: "What specific changes would you like to see?"
      placeholder: "Describe the exact changes you want to make"
    validations:
      required: true

  - type: textarea
    id: affected-areas
    attributes:
      label: "🎯 Affected Areas"
      description: "Which parts of the system will be affected?"
      placeholder: "List the files, components, or areas that need to be changed"
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: "🧪 Testing Requirements"
      description: "What testing is needed for this change?"
      placeholder: "Describe any testing that should be done to verify the enhancement"

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Any other relevant information"
      placeholder: "Add any other context that might be helpful"

  - type: markdown
    attributes:
      value: |
        ---
        📋 This enhancement request will be reviewed and prioritized by the team.
