name: "🔄 Refactor Request"
description: "Request code refactoring or technical improvements"
title: "[Refactor]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a code refactoring!

  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: "A clear and concise description of the refactoring need"
      placeholder: "What needs to be refactored?"
    validations:
      required: true

  - type: textarea
    id: current-code
    attributes:
      label: "📋 Current Code"
      description: "Describe the current code structure and issues"
      placeholder: "Describe the current code and its problems"
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: "💡 Proposed Changes"
      description: "Describe the proposed refactoring changes"
      placeholder: "Describe how you would like to refactor the code"
    validations:
      required: true

  - type: dropdown
    id: refactor-type
    attributes:
      label: "🔄 Refactor Type"
      description: "What type of refactoring is needed?"
      options:
        - "🧹 cleanup - Code cleanup and organization"
        - "⚡ optimization - Performance optimization"
        - "🔄 restructuring - Code structure changes"
        - "🔧 modernization - Modernizing legacy code"
        - "📦 modularization - Breaking into modules"
        - "🧪 testability - Improving testability"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority Level"
      description: "How important is this refactoring?"
      options:
        - "Critical - Essential for system stability"
        - "High - Important for maintainability"
        - "Medium - Valuable improvement"
        - "Low - Nice to have"
    validations:
      required: true

  - type: textarea
    id: affected-areas
    attributes:
      label: "🎯 Affected Areas"
      description: "Which parts of the codebase are affected?"
      placeholder: "List the files, components, or systems that need refactoring"
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: "⚠️ Potential Risks"
      description: "What risks should be considered?"
      placeholder: "Describe any potential risks or challenges"
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: "🧪 Testing Strategy"
      description: "How will the refactoring be tested?"
      placeholder: "Describe how to ensure the refactoring doesn't break existing functionality"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the refactoring request here"
      placeholder: "Any additional information that might be relevant"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        This refactoring request will be reviewed and prioritized by the team.
